package com.linecorp.kotlinjdsl.eclipselink.integration.querydsl.predicate

import com.linecorp.kotlinjdsl.test.integration.querydsl.predicate.AbstractCriteriaQueryDslPredicateIntegrationTest

internal class EclipselinkCriteriaQueryDslPredicateIntegrationTest : AbstractCriteriaQueryDslPredicateIntegrationTest()
