### Create Book: Hamlet
POST localhost:8080/api/v1/books
Content-Type: application/json

{
  "name": "Hamlet"
}

### Create Book: King Lear
POST localhost:8080/api/v1/books
Content-Type: application/json

{
"name": "King Lear"
}

### Create Book: Romeo and Juliet
POST localhost:8080/api/v1/books
Content-Type: application/json

{
  "name": "Romeo and Juliet"
}

### Create Book: Macbeth
POST localhost:8080/api/v1/books
Content-Type: application/json

{
  "name": "Macbeth"
}

### Find Book by id
GET localhost:8080/api/v1/books/1
Content-Type: application/json

### Find Book by name
GET localhost:8080/api/v1/books?name=et
Content-Type: application/json