package com.linecorp.kotlinjdsl.hibernate.criteriaquery

import com.linecorp.kotlinjdsl.test.integration.criteriaquery.AbstractCriteriaDeleteIntegrationTest

class HibernateCriteriaDeleteIntegrationTest : AbstractCriteriaDeleteIntegrationTest()
