package com.linecorp.kotlinjdsl.hibernate.integration.querydsl.predicate

import com.linecorp.kotlinjdsl.test.integration.querydsl.predicate.AbstractCriteriaQueryDslPredicateIntegrationTest

internal class HibernateCriteriaQueryDslPredicateIntegrationTest : AbstractCriteriaQueryDslPredicateIntegrationTest()
