package com.linecorp.kotlinjdsl.hibernate.integration.querydsl.groupby

import com.linecorp.kotlinjdsl.test.integration.querydsl.groupby.AbstractCriteriaQueryDslGroupByIntegrationTest

internal class HibernateCriteriaQueryDslGroupByIntegrationTest : AbstractCriteriaQueryDslGroupByIntegrationTest()
